package ch.eawag.chemeql;

import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;


class DeleteSpeciesDialog extends ProceedCancelDialog
{
	private static DeleteSpeciesDialog INSTANCE;
	static DeleteSpeciesDialog getInstance(ChemEQL3 parent)
	{
		if (INSTANCE == null)
			INSTANCE = new DeleteSpeciesDialog(parent);
		return INSTANCE;
	}

	private DeleteSpeciesDialog(ChemEQL3 parent)
	{
		super(parent);
		initComponents();
		speciesList.setMaximumRowCount(12);
		setLocation(600,150);
		addComponentListener(new ComponentAdapter() {
			@Override
			public void componentShown(ComponentEvent arg0)
			{
				speciesList.setModel(main.matrix.createSpeciesNamesModel());
			}
		});
	}

	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
   private void initComponents()//GEN-BEGIN:initComponents
   {
      label1 = new javax.swing.JLabel();
      speciesList = new javax.swing.JComboBox();

      getControls().setLayout(new java.awt.FlowLayout());

      setTitle("Delete Species");
      label1.setText("Delete: ");
      getControls().add(label1);

      speciesList.setMaximumRowCount(12);
      speciesList.setMinimumSize(new java.awt.Dimension(100, 25));
      speciesList.setPreferredSize(new java.awt.Dimension(150, 25));
      getControls().add(speciesList);

      pack();
   }//GEN-END:initComponents

	protected void doProceed()
	{
		((Matrix.SpeciesNamesModel)speciesList.getModel()).deleteSelectedSpecies();
		super.doProceed();
	}

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JLabel label1;
   private javax.swing.JComboBox speciesList;
   // End of variables declaration//GEN-END:variables
}
