package ch.eawag.chemeql;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import javax.swing.ButtonGroup;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JSeparator;
import javax.swing.JTextField;


class KineticsDialog extends ProceedCancelDialog implements ActionListener
{
	private static KineticsDialog INSTANCE;
	static KineticsDialog getInstance(ChemEqlGuiController parent)
	{
		if (INSTANCE == null)
			INSTANCE = new KineticsDialog(parent);
		return INSTANCE;
	}

	private JRadioButton oldSelection;		// delete this line if rb4 gets functional
	private int currentCoeffC, currentCoeffD, currentCoeffP;
	private double currentRateConst, currentKBack;
	private double currentKinTimeEnd, currentKinTimeInc;

	// Constructor for creating a bean
	public KineticsDialog()
	{
		initComponents();
	}

	private KineticsDialog(ChemEqlGuiController parent)
	{
		super(parent);
		initComponents();
		setLocation(300,100);
		rb2.addActionListener(this);
		rb3.addActionListener(this);
		rb4.addActionListener(this);
		rb5.addActionListener(this);
		rb6.addActionListener(this);
		rb7.addActionListener(this);
		rb8.addActionListener(this);
		addComponentListener(new ComponentAdapter() {
			@Override
			public void componentShown(ComponentEvent ev)
			{
				main.outputFormat = OutputFormat.INTERVAL;
				proceedButton.setEnabled(false);
				rb2.setSelected(true);
				oldSelection = rb2;					// delete this line if rb4 gets functional
				kBackLabel24.setEnabled(false);
				kBackTF25.setEnabled(false);
				coeffCTF15.requestFocusInWindow();
				coeffCTF15.setText("");
				coeffPTF18.setText("");
				coeffDTF21.setText("");
				rateKTF23.setText("");
				kBackTF25.setText("");
				intervalTF27.setText("");
				endTF29.setText("");

				kinCompC13.setModel(main.matrix.createComponentsCBModel());
				kinCompC13.setSelectedIndex(0);
				kinCompP16.setModel(main.matrix.createComponentsCBModel());
				kinCompP16.setSelectedIndex(1);
				kinCompD19.setModel(main.matrix.createComponentsCBModel());
				kinCompD19.setSelectedIndex(Math.min(2,kinCompD19.getItemCount()-1));

				enableKinCompD(false);
			}
		});
	}

	private void enableKinCompD(boolean enabled)
	{
		eductDLabel19.setEnabled(enabled);
		kinCompD19.setEnabled(enabled);
		coeffDLabel20.setEnabled(enabled);
		coeffDTF21.setEnabled(enabled);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents()
   {
      GridBagConstraints gridBagConstraints;

      rateLawGroup = new ButtonGroup();
      JPanel rateLawsPanel = new JPanel();
      JLabel zeroOrderLabel = new JLabel();
      rb2 = new JRadioButton();
      JLabel firstOrderLabel = new JLabel();
      rb3 = new JRadioButton();
      rb4 = new JRadioButton();
      JLabel secondOrderLabel = new JLabel();
      rb5 = new JRadioButton();
      rb6 = new JRadioButton();
      rb7 = new JRadioButton();
      JLabel thirdOrderLabel = new JLabel();
      rb8 = new JRadioButton();
      JSeparator seperator1 = new JSeparator();
      JPanel productsPanel = new JPanel();
      JLabel eductCLabel = new JLabel();
      kinCompC13 = new JComboBox();
      JLabel coeffCLabel = new JLabel();
      coeffCTF15 = new KeyListeningTextField()
      {
         void keyPressedActivity()
         {
            checkInputs();
         }
      };
      ;
      JLabel productLabel = new JLabel();
      kinCompP16 = new JComboBox();
      JLabel coeffPLabel = new JLabel();
      coeffPTF18 = new KeyListeningTextField()
      {
         void keyPressedActivity()
         {
            checkInputs();
         }
      };
      ;
      eductDLabel19 = new JLabel();
      kinCompD19 = new JComboBox();
      coeffDLabel20 = new JLabel();
      coeffDTF21 = new KeyListeningTextField()
      {
         void keyPressedActivity()
         {
            checkInputs();
         }
      };
      ;
      JSeparator seperator2 = new JSeparator();
      JPanel paramsPanel = new JPanel();
      JLabel rateKLabel = new JLabel();
      rateKTF23 = new KeyListeningTextField()
      {
         void keyPressedActivity()
         {
            checkInputs();
         }
      };
      ;
      JLabel intervalLabel = new JLabel();
      intervalTF27 = new KeyListeningTextField()
      {
         void keyPressedActivity()
         {
            checkInputs();
         }
      };
      ;
      kBackLabel24 = new JLabel();
      kBackTF25 = new KeyListeningTextField()
      {
         void keyPressedActivity()
         {
            checkInputs();
         }
      };
      ;
      JLabel endLabel = new JLabel();
      endTF29 = new KeyListeningTextField()
      {
         void keyPressedActivity()
         {
            checkInputs();
         }
      };
      ;

      setTitle("Kinetics");
      getContentPane().setLayout(new GridBagLayout());

      rateLawsPanel.setLayout(new GridBagLayout());

      zeroOrderLabel.setText("zero order:");
      gridBagConstraints = new GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.anchor = GridBagConstraints.WEST;
      gridBagConstraints.insets = new Insets(0, 0, 3, 0);
      rateLawsPanel.add(zeroOrderLabel, gridBagConstraints);

      rateLawGroup.add(rb2);
      rb2.setText("cC -> pP + ...       -d[C]/dt = k");
      rb2.setMargin(new Insets(0, 2, 0, 2));
      rb2.addActionListener(new ActionListener()
      {
         public void actionPerformed(ActionEvent evt)
         {
            rb2ActionPerformed(evt);
         }
      });
      gridBagConstraints = new GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.anchor = GridBagConstraints.WEST;
      gridBagConstraints.insets = new Insets(0, 10, 0, 0);
      rateLawsPanel.add(rb2, gridBagConstraints);

      firstOrderLabel.setText("first order:");
      gridBagConstraints = new GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.anchor = GridBagConstraints.WEST;
      gridBagConstraints.insets = new Insets(5, 0, 3, 0);
      rateLawsPanel.add(firstOrderLabel, gridBagConstraints);

      rateLawGroup.add(rb3);
      rb3.setText("cC -> pP + ...       -d[C]/dt = k[C]");
      rb3.setMargin(new Insets(0, 2, 0, 2));
      gridBagConstraints = new GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.anchor = GridBagConstraints.WEST;
      gridBagConstraints.insets = new Insets(0, 10, 0, 0);
      rateLawsPanel.add(rb3, gridBagConstraints);

      rateLawGroup.add(rb4);
      rb4.setText("C <-> S + ...         -d[C]/dt = k(f)[C] - k(b)[S]  (reversible)");
      rb4.setMargin(new Insets(0, 2, 0, 2));
      rb4.addActionListener(new ActionListener()
      {
         public void actionPerformed(ActionEvent evt)
         {
            rb4ActionPerformed(evt);
         }
      });
      gridBagConstraints = new GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.anchor = GridBagConstraints.WEST;
      gridBagConstraints.insets = new Insets(0, 10, 0, 0);
      rateLawsPanel.add(rb4, gridBagConstraints);

      secondOrderLabel.setText("second order:");
      gridBagConstraints = new GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.anchor = GridBagConstraints.WEST;
      gridBagConstraints.insets = new Insets(5, 0, 3, 0);
      rateLawsPanel.add(secondOrderLabel, gridBagConstraints);

      rateLawGroup.add(rb5);
      rb5.setText("cC -> pP + ...       -d[C]/dt = k[C][C]");
      rb5.setMargin(new Insets(0, 2, 0, 2));
      rb5.addActionListener(new ActionListener()
      {
         public void actionPerformed(ActionEvent evt)
         {
            rb5ActionPerformed(evt);
         }
      });
      gridBagConstraints = new GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.anchor = GridBagConstraints.WEST;
      gridBagConstraints.insets = new Insets(0, 10, 0, 0);
      rateLawsPanel.add(rb5, gridBagConstraints);

      rateLawGroup.add(rb6);
      rb6.setText("C+D -> P + ...      -d[C]/dt = k[C][D]");
      rb6.setMargin(new Insets(0, 2, 0, 2));
      rb6.addActionListener(new ActionListener()
      {
         public void actionPerformed(ActionEvent evt)
         {
            rb6ActionPerformed(evt);
         }
      });
      gridBagConstraints = new GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.anchor = GridBagConstraints.WEST;
      gridBagConstraints.insets = new Insets(0, 10, 0, 0);
      rateLawsPanel.add(rb6, gridBagConstraints);

      rateLawGroup.add(rb7);
      rb7.setText("C -> P + ...           -d[C]/dt = k[C][P]  (autocatalysis)");
      rb7.setMargin(new Insets(0, 2, 0, 2));
      gridBagConstraints = new GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.anchor = GridBagConstraints.WEST;
      gridBagConstraints.insets = new Insets(0, 10, 0, 0);
      rateLawsPanel.add(rb7, gridBagConstraints);

      thirdOrderLabel.setText("third order:");
      gridBagConstraints = new GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.anchor = GridBagConstraints.WEST;
      gridBagConstraints.insets = new Insets(5, 0, 3, 0);
      rateLawsPanel.add(thirdOrderLabel, gridBagConstraints);

      rateLawGroup.add(rb8);
      rb8.setText("cC -> pP + ...       -d[C] = k[C][C][C]");
      rb8.setMargin(new Insets(0, 2, 0, 2));
      rb8.addActionListener(new ActionListener()
      {
         public void actionPerformed(ActionEvent evt)
         {
            rb8ActionPerformed(evt);
         }
      });
      gridBagConstraints = new GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.anchor = GridBagConstraints.WEST;
      gridBagConstraints.insets = new Insets(0, 10, 0, 0);
      rateLawsPanel.add(rb8, gridBagConstraints);

      gridBagConstraints = new GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.insets = new Insets(0, 0, 10, 0);
      getContentPane().add(rateLawsPanel, gridBagConstraints);
      gridBagConstraints = new GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
      getContentPane().add(seperator1, gridBagConstraints);

      productsPanel.setLayout(new GridBagLayout());

      eductCLabel.setText("educt C:");
      gridBagConstraints = new GridBagConstraints();
      gridBagConstraints.gridy = 0;
      gridBagConstraints.anchor = GridBagConstraints.EAST;
      gridBagConstraints.insets = new Insets(0, 0, 0, 6);
      productsPanel.add(eductCLabel, gridBagConstraints);
      gridBagConstraints = new GridBagConstraints();
      gridBagConstraints.gridy = 0;
      gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
      gridBagConstraints.insets = new Insets(4, 0, 0, 12);
      productsPanel.add(kinCompC13, gridBagConstraints);

      coeffCLabel.setText("coeff c:");
      gridBagConstraints = new GridBagConstraints();
      gridBagConstraints.gridy = 0;
      gridBagConstraints.insets = new Insets(0, 0, 0, 6);
      productsPanel.add(coeffCLabel, gridBagConstraints);

      coeffCTF15.setColumns(4);
      gridBagConstraints = new GridBagConstraints();
      gridBagConstraints.gridy = 0;
      productsPanel.add(coeffCTF15, gridBagConstraints);

      productLabel.setText("product:");
      gridBagConstraints = new GridBagConstraints();
      gridBagConstraints.gridy = 1;
      gridBagConstraints.anchor = GridBagConstraints.EAST;
      gridBagConstraints.insets = new Insets(0, 0, 0, 6);
      productsPanel.add(productLabel, gridBagConstraints);
      gridBagConstraints = new GridBagConstraints();
      gridBagConstraints.gridy = 1;
      gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
      gridBagConstraints.insets = new Insets(4, 0, 0, 12);
      productsPanel.add(kinCompP16, gridBagConstraints);

      coeffPLabel.setText("coeff. p:");
      gridBagConstraints = new GridBagConstraints();
      gridBagConstraints.gridy = 1;
      gridBagConstraints.insets = new Insets(0, 0, 0, 6);
      productsPanel.add(coeffPLabel, gridBagConstraints);

      coeffPTF18.setColumns(4);
      gridBagConstraints = new GridBagConstraints();
      gridBagConstraints.gridy = 1;
      productsPanel.add(coeffPTF18, gridBagConstraints);

      eductDLabel19.setText("educt D:");
      gridBagConstraints = new GridBagConstraints();
      gridBagConstraints.gridy = 2;
      gridBagConstraints.anchor = GridBagConstraints.EAST;
      gridBagConstraints.insets = new Insets(0, 0, 0, 6);
      productsPanel.add(eductDLabel19, gridBagConstraints);
      gridBagConstraints = new GridBagConstraints();
      gridBagConstraints.gridy = 2;
      gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
      gridBagConstraints.insets = new Insets(4, 0, 0, 12);
      productsPanel.add(kinCompD19, gridBagConstraints);

      coeffDLabel20.setText("coeff. d:");
      gridBagConstraints = new GridBagConstraints();
      gridBagConstraints.gridy = 2;
      gridBagConstraints.insets = new Insets(0, 0, 0, 6);
      productsPanel.add(coeffDLabel20, gridBagConstraints);

      coeffDTF21.setColumns(4);
      gridBagConstraints = new GridBagConstraints();
      gridBagConstraints.gridy = 2;
      productsPanel.add(coeffDTF21, gridBagConstraints);

      gridBagConstraints = new GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.insets = new Insets(10, 0, 10, 0);
      getContentPane().add(productsPanel, gridBagConstraints);
      gridBagConstraints = new GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
      getContentPane().add(seperator2, gridBagConstraints);

      paramsPanel.setLayout(new GridBagLayout());

      rateKLabel.setText("rate constant k =");
      gridBagConstraints = new GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.anchor = GridBagConstraints.EAST;
      gridBagConstraints.insets = new Insets(0, 0, 0, 4);
      paramsPanel.add(rateKLabel, gridBagConstraints);

      rateKTF23.setColumns(7);
      gridBagConstraints = new GridBagConstraints();
      gridBagConstraints.gridx = 1;
      gridBagConstraints.anchor = GridBagConstraints.WEST;
      paramsPanel.add(rateKTF23, gridBagConstraints);

      intervalLabel.setText("time interval dt =");
      gridBagConstraints = new GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.anchor = GridBagConstraints.EAST;
      gridBagConstraints.insets = new Insets(0, 0, 0, 4);
      paramsPanel.add(intervalLabel, gridBagConstraints);

      intervalTF27.setColumns(4);
      gridBagConstraints = new GridBagConstraints();
      gridBagConstraints.gridx = 1;
      gridBagConstraints.anchor = GridBagConstraints.WEST;
      gridBagConstraints.insets = new Insets(4, 0, 0, 0);
      paramsPanel.add(intervalTF27, gridBagConstraints);

      kBackLabel24.setText("k(back) =");
      gridBagConstraints = new GridBagConstraints();
      gridBagConstraints.gridx = 2;
      gridBagConstraints.anchor = GridBagConstraints.EAST;
      gridBagConstraints.insets = new Insets(0, 20, 0, 4);
      paramsPanel.add(kBackLabel24, gridBagConstraints);

      kBackTF25.setColumns(7);
      gridBagConstraints = new GridBagConstraints();
      gridBagConstraints.gridx = 3;
      gridBagConstraints.anchor = GridBagConstraints.WEST;
      paramsPanel.add(kBackTF25, gridBagConstraints);

      endLabel.setText("time end =");
      gridBagConstraints = new GridBagConstraints();
      gridBagConstraints.gridx = 2;
      gridBagConstraints.anchor = GridBagConstraints.EAST;
      gridBagConstraints.insets = new Insets(0, 20, 0, 4);
      paramsPanel.add(endLabel, gridBagConstraints);

      endTF29.setColumns(4);
      gridBagConstraints = new GridBagConstraints();
      gridBagConstraints.gridx = 3;
      gridBagConstraints.anchor = GridBagConstraints.WEST;
      gridBagConstraints.insets = new Insets(4, 0, 0, 0);
      paramsPanel.add(endTF29, gridBagConstraints);

      gridBagConstraints = new GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.insets = new Insets(10, 0, 10, 0);
      getContentPane().add(paramsPanel, gridBagConstraints);

      pack();
   }// </editor-fold>//GEN-END:initComponents

	private void rb4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_rb4ActionPerformed
	{//GEN-HEADEREND:event_rb4ActionPerformed
		// Add your handling code here:
	}//GEN-LAST:event_rb4ActionPerformed

   private void rb2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_rb2ActionPerformed
   {//GEN-HEADEREND:event_rb2ActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_rb2ActionPerformed

   private void rb5ActionPerformed(ActionEvent evt)//GEN-FIRST:event_rb5ActionPerformed
   {//GEN-HEADEREND:event_rb5ActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_rb5ActionPerformed

   private void rb6ActionPerformed(ActionEvent evt)//GEN-FIRST:event_rb6ActionPerformed
   {//GEN-HEADEREND:event_rb6ActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_rb6ActionPerformed

   private void rb8ActionPerformed(ActionEvent evt)//GEN-FIRST:event_rb8ActionPerformed
   {//GEN-HEADEREND:event_rb8ActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_rb8ActionPerformed

	public void actionPerformed(ActionEvent e)
	{
		Object source = e.getSource();
		if (source == rb4)
		{
			MyTools.showWarning("Not in function yet!");	// delete this line if rb4 gets functional
			oldSelection.doClick();								// delete this line if rb4 gets functional
			return;													// delete this line if rb4 gets functional
//			kBackLabel24.setEnabled(true);					// uncomment this line if rb4 gets functional
//			kBackTF25.setEnabled(true);						// uncomment this line if rb4 gets functional
		}
		else
		{
			kBackLabel24.setEnabled(false);
			kBackTF25.setEnabled(false);
		}
		enableKinCompD(source == rb6);
		checkInputs();
		oldSelection = (JRadioButton)source;				// delete this line if rb4 gets functional
	}

	private void checkInputs()
	{
		try
		{
			currentCoeffC = Integer.parseInt(coeffCTF15.getText());
			currentCoeffP = Integer.parseInt(coeffPTF18.getText());
			if (rb6.isSelected())
				currentCoeffD = Integer.parseInt(coeffDTF21.getText());
			currentRateConst = Double.parseDouble(rateKTF23.getText());
			if (rb4.isSelected())
				currentKBack = Double.parseDouble(kBackTF25.getText());
			currentKinTimeInc = Double.parseDouble(intervalTF27.getText());
			currentKinTimeEnd = Double.parseDouble(endTF29.getText());
			proceedButton.setEnabled(true);
		}
		catch (NumberFormatException ex)
		{
			proceedButton.setEnabled(false);
		}
	}

	protected void doCancel()
	{
		/*cancel button, restore old value*/
		main.doKinetik = false;
		main.graphMI.setDisable(true);
		main.formatMenu.setDisable(true);
		main.compRangeMI.setDisable(false);
		main.logKrangeMI.setDisable(false);
		if (main.matrix.isHorHplusAndFree())
			main.pHrangeMI.setDisable(false);
		if (main.matrix.adsorption())
			main.adsRangeMI.setDisable(false);
		super.doCancel();
	}

	protected void doProceed()
	{
		if (((Component)kinCompC13.getSelectedItem()).getConc() <= 0)
			MyTools.showError("Error in matrix: Concentration of the kinetic component must be > 0!");
		else if (currentKinTimeInc > currentKinTimeEnd)
			MyTools.showError("Input error: Time increment must be smaller than time range!");
		else
		{
			main.outputFormat = OutputFormat.INTERVAL;
			main.doKinetik = true;
			main.graphMI.setDisable(false);				/*activate graphics*/
			main.formatMenu.setDisable(false);			/*activate formats*/
			main.pHrangeMI.setDisable(true);
			main.compRangeMI.setDisable(true);
			main.adsRangeMI.setDisable(true);
			main.logKrangeMI.setDisable(true);

			// set reaction order
			if (rb2.isSelected())
				main.matrix.reactionOrder = 0;
			else if (rb3.isSelected())
				main.matrix.reactionOrder = 10;
			else if (rb4.isSelected())
				main.matrix.reactionOrder = 11;
			else if (rb5.isSelected())
				main.matrix.reactionOrder = 20;
			else if (rb6.isSelected())
				main.matrix.reactionOrder = 21;
			else if (rb7.isSelected())
				main.matrix.reactionOrder = 22;
			else
			{
				// assert rb8.isSelected();
				main.matrix.reactionOrder = 30;
			}

			// set educts and products
			main.matrix.kinCompC = kinCompC13.getSelectedIndex();
			main.matrix.kinCompP = kinCompP16.getSelectedIndex();
			main.matrix.kinCompD = kinCompD19.getSelectedIndex();
			main.matrix.coeffC = currentCoeffC;
			main.matrix.coeffD = currentCoeffD;
			main.matrix.coeffP = currentCoeffP;

			// set rate and time parameters
			main.matrix.rateConst = currentRateConst;
			main.matrix.kBack = currentKBack;
			main.matrix.kinTimeInc = currentKinTimeInc;
			main.matrix.kinTimeEnd = currentKinTimeEnd;

			super.doProceed();
		}
	}
   // Variables declaration - do not modify//GEN-BEGIN:variables
   private JTextField coeffCTF15;
   private JLabel coeffDLabel20;
   private JTextField coeffDTF21;
   private JTextField coeffPTF18;
   private JLabel eductDLabel19;
   private JTextField endTF29;
   private JTextField intervalTF27;
   private JLabel kBackLabel24;
   private JTextField kBackTF25;
   private JComboBox kinCompC13;
   private JComboBox kinCompD19;
   private JComboBox kinCompP16;
   private JTextField rateKTF23;
   private ButtonGroup rateLawGroup;
   private JRadioButton rb2;
   private JRadioButton rb3;
   private JRadioButton rb4;
   private JRadioButton rb5;
   private JRadioButton rb6;
   private JRadioButton rb7;
   private JRadioButton rb8;
   // End of variables declaration//GEN-END:variables
}
