package ch.eawag.chemeql;

import javax.swing.*;


public class ProceedCancelDialog extends JDialog
{
	protected Main main;

	// Constructor for creating bean
	public ProceedCancelDialog()
	{
		this(null);
	}

	protected ProceedCancelDialog(Main main)
	{
		super(main);
		this.main = main;
		setRootPaneCheckingEnabled(false);	// required for letting the IDE sett a layout 
		initComponents();

		getRootPane().setDefaultButton(proceedButton);
	}

	public void setProceedButtonText(String value)
	{
		proceedButton.setText(value);
	}

	public String getProceedButtonText()
	{
		return proceedButton.getText();
	}

	public void setCancelButtonText(String value)
	{
		cancelButton.setText(value);
	}

	public String getCancelButtonText()
	{
		return cancelButton.getText();
	}

	public JPanel getControls()
	{
		return controlsPanel;
	}


	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
   private void initComponents()//GEN-BEGIN:initComponents
   {
      controlsPanel = new javax.swing.JPanel();
      buttonPanel = new javax.swing.JPanel();
      cancelButton = new javax.swing.JButton();
      proceedButton = new javax.swing.JButton();

      setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
      setTitle("");
      setModal(true);
      setResizable(false);
      controlsPanel.setLayout(new java.awt.GridBagLayout());

      controlsPanel.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(8, 8, 4, 8)));
      getContentPane().add(controlsPanel, java.awt.BorderLayout.CENTER);

      buttonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 16, 8));

      cancelButton.setText("Cancel");
      cancelButton.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            cancelButtonActionPerformed(evt);
         }
      });

      buttonPanel.add(cancelButton);

      proceedButton.setText("OK");
      proceedButton.setActionCommand("Ok");
      proceedButton.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            proceedButtonActionPerformed(evt);
         }
      });

      buttonPanel.add(proceedButton);

      getContentPane().add(buttonPanel, java.awt.BorderLayout.SOUTH);

      pack();
   }//GEN-END:initComponents
	
	private void proceedButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_proceedButtonActionPerformed
	{
		doProceed();
}//GEN-LAST:event_proceedButtonActionPerformed
	
	private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cancelButtonActionPerformed
	{
		doCancel();		
	}//GEN-LAST:event_cancelButtonActionPerformed

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JPanel buttonPanel;
   protected javax.swing.JButton cancelButton;
   private javax.swing.JPanel controlsPanel;
   protected javax.swing.JButton proceedButton;
   // End of variables declaration//GEN-END:variables

	protected void doProceed()
	{
		setVisible(false);
	}

	protected void doCancel()
	{
		setVisible(false);
	}
}
