package ch.eawag.chemeql;

import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;


class ProceedCancelTemplate extends ProceedCancelDialog implements ItemListener
{
	private static ProceedCancelTemplate INSTANCE;

	static ProceedCancelTemplate getInstance(ChemEqlGuiController parent) {
		if (INSTANCE == null) {
			INSTANCE = new ProceedCancelTemplate(parent);
		}
		return INSTANCE;
	}

	// Constructor for creating a bean
	public ProceedCancelTemplate() {
		initComponents();
	}

	private ProceedCancelTemplate(ChemEqlGuiController parent) {
		super(parent);
		initComponents();
		setLocation(300, 250);
		addComponentListener(new ComponentAdapter()
		{
			@Override
			public void componentShown(ComponentEvent ev) {
				proceedButton.setEnabled(false);
			}
		});
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
   private void initComponents()//GEN-BEGIN:initComponents
   {

      getContentPane().setLayout(new java.awt.GridBagLayout());

      pack();
   }//GEN-END:initComponents

	public void itemStateChanged(ItemEvent e) {
		proceedButton.setEnabled(true);
	}

	protected void doCancel() {
		super.doCancel();
	}

	protected void doProceed() {
		super.doProceed();
	}
   // Variables declaration - do not modify//GEN-BEGIN:variables
   // End of variables declaration//GEN-END:variables
}
